"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { PlusCircle, Pencil, Trash2, UserPlus } from "lucide-react";
import Link from "next/link";
import { Gang } from "@/types";

/**
 * GangsPage component for managing gang data
 * Provides CRUD functionality for gangs
 */
export default function GangsPage() {
  // State for gang data and UI controls
  const [gangs, setGangs] = useState<Gang[]>([]);
  const [isAddDialogOpen, setIsAddDialogOpen] = useState<boolean>(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState<boolean>(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState<boolean>(false);
  const [currentGang, setCurrentGang] = useState<Gang | null>(null);
  const [formData, setFormData] = useState({
    name: "",
  });

  /**
   * Load mock gang data on component mount
   * In a real application, this would fetch data from an API
   */
  useEffect(() => {
    // Mock data for demonstration
    setGangs([
      {
        id: 1,
        name: "Alpha Team",
        is_deleted: false,
        created_at: "2023-01-01T00:00:00Z",
        modified_at: "2023-01-01T00:00:00Z",
      },
      {
        id: 2,
        name: "Beta Squad",
        is_deleted: false,
        created_at: "2023-01-02T00:00:00Z",
        modified_at: "2023-01-02T00:00:00Z",
      },
      {
        id: 3,
        name: "Gamma Group",
        is_deleted: false,
        created_at: "2023-01-03T00:00:00Z",
        modified_at: "2023-01-03T00:00:00Z",
      },
    ]);
  }, []);

  /**
   * Handle form input changes
   * @param e - Input change event
   */
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  /**
   * Format date string to a more readable format
   * @param dateString - ISO date string
   * @returns Formatted date string
   */
  const formatDate = (dateString: string): string => {
    if (!dateString) return "N/A";
    return new Date(dateString).toLocaleDateString();
  };

  /**
   * Validate gang form data
   * @returns Object with validation result and error message
   */
  const validateGangForm = (): {
    isValid: boolean;
    errorMessage: string;
  } => {
    if (!formData.name.trim()) {
      return { isValid: false, errorMessage: "Gang name is required." };
    }

    return { isValid: true, errorMessage: "" };
  };

  /**
   * Handle adding a new gang
   */
  const handleAddGang = () => {
    const validation = validateGangForm();
    if (!validation.isValid) {
      // In a real app, you would show the error message to the user
      console.error(validation.errorMessage);
      return;
    }

    // Create new gang
    const newGang: Gang = {
      id: Math.floor(Math.random() * 1000), // In a real app, this would be generated by the backend
      name: formData.name,
      is_deleted: false,
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    };

    // Add to gangs list
    setGangs([...gangs, newGang]);

    // Reset form and close dialog
    setFormData({
      name: "",
    });
    setIsAddDialogOpen(false);
  };

  /**
   * Open the edit dialog for a gang
   * @param gang - The gang to edit
   */
  const openEditDialog = (gang: Gang) => {
    setCurrentGang(gang);
    setFormData({
      name: gang.name,
    });
    setIsEditDialogOpen(true);
  };

  /**
   * Handle editing an existing gang
   */
  const handleEditGang = () => {
    if (!currentGang) return;

    const validation = validateGangForm();
    if (!validation.isValid) {
      // In a real app, you would show the error message to the user
      console.error(validation.errorMessage);
      return;
    }

    // Update gang in the list
    const updatedGangs = gangs.map((gang) =>
      gang.id === currentGang.id
        ? {
            ...gang,
            name: formData.name,
            modified_at: new Date().toISOString(),
          }
        : gang
    );

    setGangs(updatedGangs);
    setIsEditDialogOpen(false);
  };

  /**
   * Open the delete dialog for a gang
   * @param gang - The gang to delete
   */
  const openDeleteDialog = (gang: Gang) => {
    setCurrentGang(gang);
    setIsDeleteDialogOpen(true);
  };

  /**
   * Handle deleting a gang
   */
  const handleDeleteGang = () => {
    if (!currentGang) return;

    // In a real app, you might want to soft delete by setting is_deleted to true
    // Here we're removing from the array for simplicity
    const updatedGangs = gangs.filter((gang) => gang.id !== currentGang.id);

    setGangs(updatedGangs);
    setIsDeleteDialogOpen(false);
  };

  return (
    <div className="container mx-auto py-10">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl font-bold">Gangs</CardTitle>
          <CardDescription>
            Manage your work gangs and their members.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex justify-end mb-4">
            <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
              <DialogTrigger asChild>
                <Button className="flex items-center gap-2">
                  <PlusCircle className="h-4 w-4" />
                  Add Gang
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Add Gang</DialogTitle>
                  <DialogDescription>
                    Add a new work gang to your database.
                  </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="name" className="text-right">
                      Gang Name
                    </Label>
                    <Input
                      id="name"
                      name="name"
                      value={formData.name}
                      onChange={handleInputChange}
                      className="col-span-3"
                      required
                    />
                  </div>
                </div>
                <DialogFooter>
                  <Button
                    variant="outline"
                    onClick={() => setIsAddDialogOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button onClick={handleAddGang}>Create</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Gang Name</TableHead>
                <TableHead>Created</TableHead>
                <TableHead>Last Modified</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {gangs.map((gang) => (
                <TableRow key={gang.id}>
                  <TableCell className="font-medium">{gang.name}</TableCell>
                  <TableCell>{formatDate(gang.created_at)}</TableCell>
                  <TableCell>{formatDate(gang.modified_at)}</TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        className="flex items-center gap-1"
                        asChild
                      >
                        <Link href={`/gangs/${gang.id}`}>
                          <UserPlus className="h-4 w-4 mr-1" />
                          Engineers
                        </Link>
                      </Button>
                      <Button
                        variant="outline"
                        size="icon"
                        onClick={() => openEditDialog(gang)}
                      >
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="destructive"
                        size="icon"
                        onClick={() => openDeleteDialog(gang)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {gangs.length === 0 && (
                <TableRow>
                  <TableCell colSpan={4} className="text-center py-4">
                    No gangs found. Add a gang to get started.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Edit Gang Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Gang</DialogTitle>
            <DialogDescription>Update the gang information.</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="edit-name" className="text-right">
                Gang Name
              </Label>
              <Input
                id="edit-name"
                name="name"
                value={formData.name}
                onChange={handleInputChange}
                className="col-span-3"
                required
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
            >
              Cancel
            </Button>
            <Button onClick={handleEditGang}>Save Changes</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Confirm Deletion</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete {currentGang?.name}? This action
              cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsDeleteDialogOpen(false)}
            >
              Cancel
            </Button>
            <Button variant="destructive" onClick={handleDeleteGang}>
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
