"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { PlusCircle, Pencil, Trash2 } from "lucide-react";
import { Engineer } from "@/types";

/**
 * EngineersPage component for managing engineer data
 * Provides CRUD functionality for engineers
 */
export default function EngineersPage() {
  // State for engineer data and UI controls
  const [engineers, setEngineers] = useState<Engineer[]>([]);
  const [isAddDialogOpen, setIsAddDialogOpen] = useState<boolean>(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState<boolean>(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState<boolean>(false);
  const [currentEngineer, setCurrentEngineer] = useState<Engineer | null>(null);
  const [formData, setFormData] = useState({
    name: "",
  });

  /**
   * Load mock engineer data on component mount
   * In a real application, this would fetch data from an API
   */
  useEffect(() => {
    // Mock data for demonstration
    setEngineers([
      {
        id: 1,
        name: "Alex Johnson",
        is_deleted: false,
        created_at: "2023-01-01T00:00:00Z",
        modified_at: "2023-01-01T00:00:00Z",
      },
      {
        id: 2,
        name: "Maria Garcia",
        is_deleted: false,
        created_at: "2023-01-02T00:00:00Z",
        modified_at: "2023-01-02T00:00:00Z",
      },
      {
        id: 3,
        name: "David Kim",
        is_deleted: false,
        created_at: "2023-01-03T00:00:00Z",
        modified_at: "2023-01-03T00:00:00Z",
      },
    ]);
  }, []);

  /**
   * Handle form input changes
   * @param e - Input change event
   */
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  /**
   * Format date string to a more readable format
   * @param dateString - ISO date string
   * @returns Formatted date string
   */
  const formatDate = (dateString: string): string => {
    if (!dateString) return "N/A";
    return new Date(dateString).toLocaleDateString();
  };

  /**
   * Validate engineer form data
   * @returns Object with validation result and error message
   */
  const validateEngineerForm = (): {
    isValid: boolean;
    errorMessage: string;
  } => {
    if (!formData.name.trim()) {
      return { isValid: false, errorMessage: "Engineer name is required." };
    }

    return { isValid: true, errorMessage: "" };
  };

  /**
   * Handle adding a new engineer
   */
  const handleAddEngineer = () => {
    const validation = validateEngineerForm();
    if (!validation.isValid) {
      // In a real app, you would show the error message to the user
      console.error(validation.errorMessage);
      return;
    }

    // Create new engineer
    const newEngineer: Engineer = {
      id: Math.floor(Math.random() * 1000), // In a real app, this would be generated by the backend
      name: formData.name,
      is_deleted: false,
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    };

    // Add to engineers list
    setEngineers([...engineers, newEngineer]);

    // Reset form and close dialog
    setFormData({
      name: "",
    });
    setIsAddDialogOpen(false);
  };

  /**
   * Open the edit dialog for an engineer
   * @param engineer - The engineer to edit
   */
  const openEditDialog = (engineer: Engineer) => {
    setCurrentEngineer(engineer);
    setFormData({
      name: engineer.name,
    });
    setIsEditDialogOpen(true);
  };

  /**
   * Handle editing an existing engineer
   */
  const handleEditEngineer = () => {
    if (!currentEngineer) return;

    const validation = validateEngineerForm();
    if (!validation.isValid) {
      // In a real app, you would show the error message to the user
      console.error(validation.errorMessage);
      return;
    }

    // Update engineer in the list
    const updatedEngineers = engineers.map((engineer) =>
      engineer.id === currentEngineer.id
        ? {
            ...engineer,
            name: formData.name,
            modified_at: new Date().toISOString(),
          }
        : engineer
    );

    setEngineers(updatedEngineers);
    setIsEditDialogOpen(false);
  };

  /**
   * Open the delete dialog for an engineer
   * @param engineer - The engineer to delete
   */
  const openDeleteDialog = (engineer: Engineer) => {
    setCurrentEngineer(engineer);
    setIsDeleteDialogOpen(true);
  };

  /**
   * Handle deleting an engineer
   */
  const handleDeleteEngineer = () => {
    if (!currentEngineer) return;

    // In a real app, you might want to soft delete by setting is_deleted to true
    // Here we're removing from the array for simplicity
    const updatedEngineers = engineers.filter(
      (engineer) => engineer.id !== currentEngineer.id
    );

    setEngineers(updatedEngineers);
    setIsDeleteDialogOpen(false);
  };

  return (
    <div className="container mx-auto py-10">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl font-bold">Engineers</CardTitle>
          <CardDescription>
            Manage your engineers who work on projects.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex justify-end mb-4">
            <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
              <DialogTrigger asChild>
                <Button className="flex items-center gap-2">
                  <PlusCircle className="h-4 w-4" />
                  Add Engineer
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Add Engineer</DialogTitle>
                  <DialogDescription>
                    Add a new engineer to your database.
                  </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="name" className="text-right">
                      Engineer Name
                    </Label>
                    <Input
                      id="name"
                      name="name"
                      value={formData.name}
                      onChange={handleInputChange}
                      className="col-span-3"
                      required
                    />
                  </div>
                </div>
                <DialogFooter>
                  <Button
                    variant="outline"
                    onClick={() => setIsAddDialogOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button onClick={handleAddEngineer}>Create</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Engineer Name</TableHead>
                <TableHead>Created</TableHead>
                <TableHead>Last Modified</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {engineers.map((engineer) => (
                <TableRow key={engineer.id}>
                  <TableCell className="font-medium">{engineer.name}</TableCell>
                  <TableCell>{formatDate(engineer.created_at)}</TableCell>
                  <TableCell>{formatDate(engineer.modified_at)}</TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      <Button
                        variant="outline"
                        size="icon"
                        onClick={() => openEditDialog(engineer)}
                      >
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="destructive"
                        size="icon"
                        onClick={() => openDeleteDialog(engineer)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {engineers.length === 0 && (
                <TableRow>
                  <TableCell colSpan={4} className="text-center py-4">
                    No engineers found. Add an engineer to get started.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Edit Engineer Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Engineer</DialogTitle>
            <DialogDescription>
              Update the engineer information.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="edit-name" className="text-right">
                Engineer Name
              </Label>
              <Input
                id="edit-name"
                name="name"
                value={formData.name}
                onChange={handleInputChange}
                className="col-span-3"
                required
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
            >
              Cancel
            </Button>
            <Button onClick={handleEditEngineer}>Save Changes</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Confirm Deletion</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete {currentEngineer?.name}? This
              action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsDeleteDialogOpen(false)}
            >
              Cancel
            </Button>
            <Button variant="destructive" onClick={handleDeleteEngineer}>
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
