"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { PlusCircle, Pencil, Trash2 } from "lucide-react";
import { Product } from "@/types";

/**
 * ProductsPage component for managing product data
 * Provides CRUD functionality for products
 */
export default function ProductsPage() {
  // State for product data and UI controls
  const [products, setProducts] = useState<Product[]>([]);
  const [isAddDialogOpen, setIsAddDialogOpen] = useState<boolean>(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState<boolean>(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState<boolean>(false);
  const [currentProduct, setCurrentProduct] = useState<Product | null>(null);
  const [formData, setFormData] = useState({
    name: "",
    code: "",
    description: "",
    unit_of_measure: "",
  });

  /**
   * Load mock product data on component mount
   * In a real application, this would fetch data from an API
   */
  useEffect(() => {
    // Mock data for demonstration
    setProducts([
      {
        id: 1,
        name: "Basic Installation",
        code: "INST-001",
        description: "Standard installation service",
        unit_of_measure: "Hour",
        is_deleted: false,
        created_at: "2023-01-01T00:00:00Z",
        modified_at: "2023-01-01T00:00:00Z",
      },
      {
        id: 2,
        name: "Premium Support",
        code: "SUPP-002",
        description: "24/7 premium support package",
        unit_of_measure: "Month",
        is_deleted: false,
        created_at: "2023-01-02T00:00:00Z",
        modified_at: "2023-01-02T00:00:00Z",
      },
      {
        id: 3,
        name: "System Maintenance",
        code: "MAINT-003",
        description: "Regular system maintenance",
        unit_of_measure: "Hour",
        is_deleted: false,
        created_at: "2023-01-03T00:00:00Z",
        modified_at: "2023-01-03T00:00:00Z",
      },
    ]);
  }, []);

  /**
   * Handle form input changes
   * @param e - Input change event
   */
  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  /**
   * Format date string to a more readable format
   * @param dateString - ISO date string
   * @returns Formatted date string
   */
  const formatDate = (dateString: string): string => {
    if (!dateString) return "N/A";
    return new Date(dateString).toLocaleDateString();
  };

  /**
   * Validate product form data
   * @returns Object with validation result and error message
   */
  const validateProductForm = (): {
    isValid: boolean;
    errorMessage: string;
  } => {
    if (!formData.name.trim()) {
      return { isValid: false, errorMessage: "Product name is required." };
    }

    if (!formData.code.trim()) {
      return { isValid: false, errorMessage: "Product code is required." };
    }

    if (!formData.unit_of_measure.trim()) {
      return {
        isValid: false,
        errorMessage: "Unit of measure is required.",
      };
    }

    // Check for duplicate product code
    if (
      currentProduct?.code !== formData.code &&
      products.some((product) => product.code === formData.code)
    ) {
      return {
        isValid: false,
        errorMessage: "Product code must be unique.",
      };
    }

    return { isValid: true, errorMessage: "" };
  };

  /**
   * Handle adding a new product
   */
  const handleAddProduct = () => {
    const validation = validateProductForm();
    if (!validation.isValid) {
      // In a real app, you would show the error message to the user
      console.error(validation.errorMessage);
      return;
    }

    // Create new product
    const newProduct: Product = {
      id: Math.floor(Math.random() * 1000), // In a real app, this would be generated by the backend
      name: formData.name,
      code: formData.code,
      description: formData.description,
      unit_of_measure: formData.unit_of_measure,
      is_deleted: false,
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    };

    // Add to products list
    setProducts([...products, newProduct]);

    // Reset form and close dialog
    setFormData({
      name: "",
      code: "",
      description: "",
      unit_of_measure: "",
    });
    setIsAddDialogOpen(false);
  };

  /**
   * Open the edit dialog for a product
   * @param product - The product to edit
   */
  const openEditDialog = (product: Product) => {
    setCurrentProduct(product);
    setFormData({
      name: product.name,
      code: product.code,
      description: product.description,
      unit_of_measure: product.unit_of_measure,
    });
    setIsEditDialogOpen(true);
  };

  /**
   * Handle editing an existing product
   */
  const handleEditProduct = () => {
    if (!currentProduct) return;

    const validation = validateProductForm();
    if (!validation.isValid) {
      // In a real app, you would show the error message to the user
      console.error(validation.errorMessage);
      return;
    }

    // Update product in the list
    const updatedProducts = products.map((product) =>
      product.id === currentProduct.id
        ? {
            ...product,
            name: formData.name,
            code: formData.code,
            description: formData.description,
            unit_of_measure: formData.unit_of_measure,
            modified_at: new Date().toISOString(),
          }
        : product
    );

    setProducts(updatedProducts);
    setIsEditDialogOpen(false);
  };

  /**
   * Open the delete dialog for a product
   * @param product - The product to delete
   */
  const openDeleteDialog = (product: Product) => {
    setCurrentProduct(product);
    setIsDeleteDialogOpen(true);
  };

  /**
   * Handle deleting a product
   */
  const handleDeleteProduct = () => {
    if (!currentProduct) return;

    // In a real app, you might want to soft delete by setting is_deleted to true
    // Here we're removing from the array for simplicity
    const updatedProducts = products.filter(
      (product) => product.id !== currentProduct.id
    );

    setProducts(updatedProducts);
    setIsDeleteDialogOpen(false);
  };

  return (
    <div className="container mx-auto py-10">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl font-bold">Products</CardTitle>
          <CardDescription>
            Manage your product catalog and services.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex justify-end mb-4">
            <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
              <DialogTrigger asChild>
                <Button className="flex items-center gap-2">
                  <PlusCircle className="h-4 w-4" />
                  Add Product
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Add Product</DialogTitle>
                  <DialogDescription>
                    Add a new product to your catalog.
                  </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="name" className="text-right">
                      Product Name
                    </Label>
                    <Input
                      id="name"
                      name="name"
                      value={formData.name}
                      onChange={handleInputChange}
                      className="col-span-3"
                      required
                    />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="code" className="text-right">
                      Product Code
                    </Label>
                    <Input
                      id="code"
                      name="code"
                      value={formData.code}
                      onChange={handleInputChange}
                      className="col-span-3"
                      required
                    />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="description" className="text-right">
                      Description
                    </Label>
                    <Textarea
                      id="description"
                      name="description"
                      value={formData.description}
                      onChange={handleInputChange}
                      className="col-span-3"
                      rows={3}
                    />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="unit_of_measure" className="text-right">
                      Unit of Measure
                    </Label>
                    <Input
                      id="unit_of_measure"
                      name="unit_of_measure"
                      value={formData.unit_of_measure}
                      onChange={handleInputChange}
                      className="col-span-3"
                      required
                    />
                  </div>
                </div>
                <DialogFooter>
                  <Button
                    variant="outline"
                    onClick={() => setIsAddDialogOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button onClick={handleAddProduct}>Create</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Code</TableHead>
                <TableHead>Unit</TableHead>
                <TableHead>Description</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {products.map((product) => (
                <TableRow key={product.id}>
                  <TableCell className="font-medium">{product.name}</TableCell>
                  <TableCell>{product.code}</TableCell>
                  <TableCell>{product.unit_of_measure}</TableCell>
                  <TableCell>
                    {product.description.length > 50
                      ? `${product.description.substring(0, 50)}...`
                      : product.description}
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      <Button
                        variant="outline"
                        size="icon"
                        onClick={() => openEditDialog(product)}
                      >
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="destructive"
                        size="icon"
                        onClick={() => openDeleteDialog(product)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {products.length === 0 && (
                <TableRow>
                  <TableCell colSpan={5} className="text-center py-4">
                    No products found. Add a product to get started.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Edit Product Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Product</DialogTitle>
            <DialogDescription>
              Update the product information.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="edit-name" className="text-right">
                Product Name
              </Label>
              <Input
                id="edit-name"
                name="name"
                value={formData.name}
                onChange={handleInputChange}
                className="col-span-3"
                required
              />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="edit-code" className="text-right">
                Product Code
              </Label>
              <Input
                id="edit-code"
                name="code"
                value={formData.code}
                onChange={handleInputChange}
                className="col-span-3"
                required
              />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="edit-description" className="text-right">
                Description
              </Label>
              <Textarea
                id="edit-description"
                name="description"
                value={formData.description}
                onChange={handleInputChange}
                className="col-span-3"
                rows={3}
              />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="edit-unit_of_measure" className="text-right">
                Unit of Measure
              </Label>
              <Input
                id="edit-unit_of_measure"
                name="unit_of_measure"
                value={formData.unit_of_measure}
                onChange={handleInputChange}
                className="col-span-3"
                required
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
            >
              Cancel
            </Button>
            <Button onClick={handleEditProduct}>Save Changes</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Confirm Deletion</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete {currentProduct?.name}? This
              action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsDeleteDialogOpen(false)}
            >
              Cancel
            </Button>
            <Button variant="destructive" onClick={handleDeleteProduct}>
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
